### ISSUE TITLE
Auth policy should support regex/glob for caller ids

### ISSUE THREAD

**Issue by ExalDraen** [choria-plugins/action-policy#7]
## Summary 
Currently, the action policy framework only supports two kinds of caller ids: match anything (`*`) and exact matches (e.g. `choria=rip.mcollective`). 

This is described in the Policy File Format section of `action-policy` which states: 

> Caller ID --- must be either * (always matches) or a space-separated list of caller ID strings (see below)

It would be very useful to be able to define more fine-grained wild cards to make it easier to define policies - for example glob or regex matches.

## Reasoning

For example, when using the [choria AAA service](https://github.com/choria-io/aaasvc), users must have defined in the AAA service _and_ given explicit access to resources using action policy, which adds overhead and makes the solution more fragile. 
If action policy could match on caller id patterns, then usernames could be made to follow pattern (say `username.aaasvc`) and the policies could match on the `.aaasvc` suffix which would eliminate the need to update policies as users are added / removed from AAA. 

## Proposal 

Note that both of the changes below are potentially breaking as far as I understand: they both entail interpreting caller ids that previously would have simply been string compared as something else. 

### Minimal option

In the interest of making a _minimal_ change the matching logic could be changed to allow for glob patterns using `File.fnmatch` ([ruby docs](https://ruby-doc.org/core-2.5.0/File.html#method-c-fnmatch))

A policy might thus look like (using `|` instead of tabs for illustration only, tabs are hard to type ...)
```
policy default deny
allow | choria=ginkgo.mcollective| * | * | *
allow | up=puppetadmin.aaasvc | * | * | *
allow | *.admin.aaasvc | status enable disable | * | *
allow | *.staging.aaasvc *.dev.aaasvc | status | * | *
```
which would: 
* allow  `ginkgo.mcollective` and `up=puppetadmin.aaasvc` all actions with any class & fact,
* allow any `.admin.aaasvc` caller id the status, enable & disable actions
* allow any `.staging.aaasvc` or `.dev.aaasvc` caller id the status action only

### More fully featured 

Using a regular expression match would make the wildcarding even more flexible at the cost of making the syntax a bit more complex. 

Perhaps something like this 
```
policy default deny
allow | choria=ginkgo.mcollective| * | * | *
allow | up=puppetadmin.aaasvc | * | * | *
allow | /admin\.aaasvc$/ | status enable disable | * | *
allow | /staging\.aaasvc$/ /dev\.aaasvc$/ | status | * | *
```
which would have the same meaning as above

**Comment by ripienaar** [comment]
Using a regex will be best and avoid the backwards compat issues - no userid could start with `/` but regex would - so the new code paths would only be hit for people with regex user ids? 

What do you think?

**Comment by ripienaar** [comment]
@ExalDraen let me know your thoughts about the PR but to me it seems this will do what you want? If this works for you I'll do the same in go

**Comment by ripienaar** [comment]
I did the go code to match anyway https://github.com/choria-io/mcorpc-agent-provider/pull/135 (which I merged by accident, but I think this is the right approach)

**Comment by ExalDraen** [comment]
Cool, regex matches are fine by me, I didn't know the userid syntax rules so I wasn't sure what was more likely to be compatible.

**Comment by ripienaar** [comment]
OK then, I'll release this later today, thank you

**Comment by ripienaar** [comment]
@ExalDraen the go nightly for tomorrow will have it also included
